# Generated by Django 4.2.23 on 2026-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pickup_smartbin_wastereport_delete_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='image',
        ),
        migrations.AddField(
            model_name='wastereport',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
