name: Selenium Automation Framework

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  selenium-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Automation/requirements.txt

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run Tests
      working-directory: Automation
      run: |
        pytest

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Selenium-Report
        path: Automation/reports/