name: Selenium Automation CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Django Migrations
        run: |
          python manage.py migrate

      - name: Create Test User
        run: |
          python manage.py shell <<EOF
          from django.contrib.auth import get_user_model

          User = get_user_model()

          username = "abhijitdhumale2909@gmail.com"
          email = "abhijitdhumale2909@gmail.com"
          password = "Abhi2909"

          if not User.objects.filter(username=username).exists():
            User.objects.create_user(
                username=username,
                email=email,
                password=password
            )

          print("Test user ready.")
          EOF

      - name: Start Django Server
        run: |
          python manage.py runserver 127.0.0.1:8000 &
          sleep 10

      - name: Run Selenium Tests
        working-directory: Automation
        run: |
          pytest

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Selenium-HTML-Report
          path: Automation/reports/